<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SignalRadar.Application/SignalRadar.Application.csproj" />
    <ProjectReference Include="../SignalRadar.Bot/SignalRadar.Bot.csproj" />
    <ProjectReference Include="../SignalRadar.Infrastructure/SignalRadar.Infrastructure.csproj" />
  </ItemGroup>
</Project>
